// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: auth_select_user.sql

package database

import (
	"context"
)

const selectUserInfo = `-- name: SelectUserInfo :one
SELECT id, created_at, updated_at, email, hashed_password FROM users
WHERE email = $1
`

func (q *Queries) SelectUserInfo(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, selectUserInfo, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}
