// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: update_subscription.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateSubscription = `-- name: UpdateSubscription :exec
UPDATE users
SET is_chirpy_red = TRUE
WHERE id = $1
`

func (q *Queries) UpdateSubscription(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateSubscription, id)
	return err
}
