// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: update_user_info.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUserInfo = `-- name: UpdateUserInfo :exec
UPDATE users
SET hashed_password = $2
WHERE id = $1
`

type UpdateUserInfoParams struct {
	ID             uuid.UUID
	HashedPassword string
}

func (q *Queries) UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) error {
	_, err := q.db.ExecContext(ctx, updateUserInfo, arg.ID, arg.HashedPassword)
	return err
}
